export const ROUTES = {
    login: '/login',
    register: '/register',
    dashboard: '/dashboard',
    nomenclature: '/nomenclature',
    bibliography: '/bibliography',
    occurrences: '/occurrences',
    projects: '/projects',
    reports: '/reports',
    logout: '/logout',
    admin: '/administrator',
    profile: '/profile',
    bibliographyId: '/bibliography/:id',
    bibliographyCreate: '/bibliography/new',
    bibliographyFileUpload: '/bibliography/new_file_upload',
    bibliographyEdit: '/bibliography/edit/:id',
    nomenclatureId: '/nomenclature/:id',
    nomenclatureCreate: '/nomenclature/new',
    nomenclatureEdit: '/nomenclature/edit/:id',
    nomenclatureFileUpload: '/nomenclature/new_file_upload',

}