import Box from "@mui/material/Box";
import { COLORS, BORDER, FONT_SIZES } from '../../constants/ui.ts';
import Typography from '@mui/material/Typography';
import FormField from "../../components/FormField.tsx";
import {useEffect, useState} from "react";
import { getHelperText } from "../../utils/formFieldHelpers.ts";
import { formatLabel } from "../../utils/helperFunctions.ts";
import ListInput from "../../components/ListInput.tsx";
import StyledButton from "../../components/StyledButton.tsx";
import SaveIcon from '@mui/icons-material/Save';